= JetPack Compose
Herzog Nathalie
ifndef::sourcedir[:sourcedir: ../src/main/java]
ifndef::imagesdir[:imagesdir: images]
ifndef::backend[:backend: html5]
:icons: font
:toc:

== Introduction
Jetpack Compose is a modern toolkit for building native Android UI. Jetpack Compose simplifies and accelerates UI development on Android with less code, powerful tools, and intuitive Kotlin APIs.

Jetpack Compose is totally declarative programming, which means you can describe your user interface by invoking a set of composable.

== Benefits
* **Declarative:** It is fully declarative so that you can describe your UI components by calling some predefined functions.
* **Compatible:** It is easily compatible with the existing views present in Android.
* **Increase development speed:** Previously developers have to work on the XML file and Kotlin file. But with the help of jetpack compose this becomes easy and developers only have to work on the Kotlin files that’s why it will help developers in increasing development speed.
* **Concise and Idiomatic Kotlin:** Jetpack Compose built the UI with the benefit that Kotlin brings.
* **Easy to maintain:** As the codebase of any application is present in a single file. It becomes easy to manage and handle the codebase of the application.
* **Written in Kotlin:** The application written using jetpack compose uses 100 % of Kotlin programming language.

== Dynamic Content
Because composable functions are written in Kotlin instead of XML, they can be as dynamic as any other Kotlin code.

You can use if statements to decide if you want to show a particular UI element. You can use loops. You can call helper functions. You have the full flexibility of the underlying language. This power and flexibility is one of the key advantages of Jetpack Compose.

== Recomposition
In an imperative UI model, to change a widget, you call a setter on the widget to change its internal state. In Compose, you call the composable function again with new data. Doing so causes the function to be recomposed--the widgets emitted by the function are redrawn, if necessary, with new data. The Compose framework can intelligently recompose only the components that changed.

Example:
[source,kotlin]
----
@Composable
fun ClickCounter(clicks: Int, onClick: () -> Unit) {
    Button(onClick = onClick) {
        Text("I've been clicked $clicks times")
    }
}
----

Every time the button is clicked, the caller updates the value of clicks. Compose calls the lambda with the Text function again to show the new value; this process is called recomposition. Other functions that don't depend on the value are not recomposed.

== Adding JetPack to App

First, make sure you are using **Android Studio Arctic Fox**, a Kotlin version of at least **1.5.31** and a **minimum API level of 21**.

=== Enable Compose
[source,kotlin]
----
   buildFeatures {
        compose true
    }
----

=== Add the dependencies
[source,kotling]
----
dependencies {
    // Integration with activities
    implementation 'androidx.activity:activity-compose:1.3.1'
    // Compose Material Design
    implementation 'androidx.compose.material:material:1.0.5'
    // Animations
    implementation 'androidx.compose.animation:animation:1.0.5'
    // Tooling support (Previews, etc.)
    implementation 'androidx.compose.ui:ui-tooling:1.0.5'
    // Integration with ViewModels
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha07'
    // UI Tests
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4:1.0.5'

    // When using a MDC theme
    implementation "com.google.android.material:compose-theme-adapter:1.0.5"

    // When using a AppCompat theme
    implementation "com.google.accompanist:accompanist-appcompat-theme:0.16.0"
}
----

=== Migrate

Use
[source,kotlin]
----
  <androidx.compose.ui.platform.ComposeView>
----

instead of **View**.

Create composable functions by using the annotation **@Composable**:
[source,kotlin]
----
@Composable
fun Greeting(name: String) {
    Text(text = "Hello $name!")
}
----

Set it as the content of your activity:
[source,kotlin]
----
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            Greeting("World")
        }
    }
}
----